import { Inter } from "next/font/google";
import { Providers } from "./redux/providers.js";
import "./globals.css";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster/>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
